// Gallery.jsx
// Premium gallery page template generated by ChatGPT.
// Update import paths if your project structure differs.

import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Header from "./Header";
import Footer from "./Footer";

export default function Gallery() {
  const [cases, setCases] = useState([]);
  const [category, setCategory] = useState("All");
  const [loading, setLoading] = useState(true);
  const [selectedImage, setSelectedImage] = useState(null);

  useEffect(() => {
    fetch("https://dental-backend-2vs2.onrender.com/api/gallery")
      .then((res) => res.json())
      .then((data) => {
        setCases(data);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const categories = [
    "All",
    ...new Set(cases.map((item) => item.category)),
  ];

  const filtered =
    category === "All"
      ? cases
      : cases.filter((item) => item.category === category);

  return (
    <>
      <Header />

      <section className="bg-[#fffaf4] pt-36 pb-24 border-b border-logo-orange-100">
        <div className="max-w-7xl mx-auto px-6">
          <span className="font-mono text-[11px] uppercase tracking-[0.3em] text-logo-orange-600">
            Real Patients • Real Results
          </span>

          <h1 className="mt-6 font-serif text-5xl md:text-7xl leading-none text-logo-auburn-500">
            Smile transformations
            <span className="italic text-logo-orange-500"> you can trust.</span>
          </h1>

          <p className="mt-6 max-w-2xl text-slate-600 text-lg">
            Explore documented before-and-after cases from our patients and
            discover realistic treatment outcomes.
          </p>

          <div className="grid grid-cols-3 gap-8 mt-12 max-w-2xl">
            <div>
              <h3 className="text-4xl font-bold text-logo-auburn-500">500+</h3>
              <p className="text-xs uppercase tracking-widest text-slate-500">
                Cases
              </p>
            </div>

            <div>
              <h3 className="text-4xl font-bold text-logo-auburn-500">4.9</h3>
              <p className="text-xs uppercase tracking-widest text-slate-500">
                Rating
              </p>
            </div>

            <div>
              <h3 className="text-4xl font-bold text-logo-auburn-500">97%</h3>
              <p className="text-xs uppercase tracking-widest text-slate-500">
                Satisfaction
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-[#fffaf4] py-20">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-12">
            <span className="font-mono text-xs uppercase tracking-[0.3em] text-logo-orange-600">
              Outcomes by Treatment
            </span>

            <h2 className="mt-4 text-4xl font-display text-logo-auburn-500">
              Filter the gallery
            </h2>
          </div>

          <div className="flex flex-wrap justify-center gap-3 mb-16">
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setCategory(cat)}
                className={`rounded-full px-5 py-3 text-sm transition-all ${
                  category === cat
                    ? "bg-logo-auburn-500 text-white"
                    : "bg-white border border-logo-orange-100 text-slate-600"
                }`}
              >
                {cat}
              </button>
            ))}
          </div>

          {loading ? (
            <div className="flex justify-center py-20">
              <div className="h-12 w-12 animate-spin rounded-full border-4 border-logo-orange-500 border-t-transparent"></div>
            </div>
          ) : (
            <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-8">
              {filtered.map((item) => (
                <div
                  key={item._id}
                  className="overflow-hidden rounded-[28px] border border-logo-orange-100 bg-white shadow-sm hover:shadow-xl transition-all"
                >
                  <div className="grid grid-cols-2">
                    <div
                      className="relative cursor-pointer"
                      onClick={() => setSelectedImage(item.beforeImage)}
                    >
                      <img
                        src={item.beforeImage}
                        alt="Before"
                        className="h-72 w-full object-cover"
                      />
                      <div className="absolute left-3 top-3 rounded-full bg-logo-auburn-500 px-3 py-1 text-[10px] font-bold uppercase text-white">
                        Before
                      </div>
                    </div>

                    <div
                      className="relative cursor-pointer"
                      onClick={() => setSelectedImage(item.afterImage)}
                    >
                      <img
                        src={item.afterImage}
                        alt="After"
                        className="h-72 w-full object-cover"
                      />
                      <div className="absolute right-3 top-3 rounded-full bg-logo-orange-500 px-3 py-1 text-[10px] font-bold uppercase text-white">
                        After
                      </div>
                    </div>
                  </div>

                  <div className="p-5">
                    <p className="font-mono text-[10px] uppercase tracking-widest text-logo-orange-600">
                      {item.category}
                    </p>

                    <h3 className="mt-2 text-xl font-semibold text-logo-auburn-500">
                      {item.title}
                    </h3>

                    <p className="mt-3 text-sm text-slate-500">
                      {item.description || "Patient transformation result."}
                    </p>

                    <button
                      onClick={() => setSelectedImage(item.afterImage)}
                      className="mt-5 w-full rounded-xl bg-logo-orange-500 py-3 text-white hover:bg-logo-orange-600"
                    >
                      View Full Result
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </section>

      <section className="bg-logo-auburn-700 py-24 text-center text-white">
        <div className="max-w-3xl mx-auto px-6">
          <span className="font-mono text-xs uppercase tracking-[0.3em] text-logo-orange-200">
            Ready When You Are
          </span>

          <h2 className="mt-6 text-5xl font-display">
            Book a consultation to discuss your smile.
          </h2>

          <p className="mt-6 text-white/70">
            Meet our specialists and receive a personalized treatment plan.
          </p>

          <Link
            to="/contact"
            className="inline-flex mt-8 rounded-full bg-white px-8 py-4 font-semibold text-logo-auburn-700"
          >
            Book Consultation
          </Link>
        </div>
      </section>

      {selectedImage && (
        <div
          className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/90 p-4"
          onClick={() => setSelectedImage(null)}
        >
          <img
            src={selectedImage}
            alt="Preview"
            className="max-h-[90vh] max-w-[90vw] rounded-2xl"
          />
        </div>
      )}

      <Footer />
    </>
  );
}
